### ISSUE TITLE
Null Pointer Exception caused by BlackboardCollector

### ISSUE THREAD

**Issue by applebyter** [BraeWebb/chalkbox#15]
When processing the sample file "2019s2a2-gradebook.zip" a null pointer exception is raised. This is due to a logic fault in `BlackboardCollector.readSubmissionFile`. The local variable `lastKey` is initialised to null. The logic only gives `lastKey` a value in the `else if (line.contains(":"))` branch of the conditional logic. The `else` branch uses `lastKey`, which is causing the null pointer exception, as it passes it as the key to `Data.set`.

The stack trace is:
`java.lang.reflect.InvocationTargetException`  \
`        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`  \
`        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)`  \
`        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)`  \
`        at java.lang.reflect.Method.invoke(Unknown Source)`  \
`        at chalkbox.api.ChalkBox.executeCollection(ChalkBox.java:316)`  \
`        at chalkbox.api.ChalkBox.run(ChalkBox.java:165)`  
`        at chalkbox.api.ChalkBox.main(ChalkBox.java:456)`  
`Caused by: java.lang.NullPointerException`  
`        at chalkbox.api.collections.Data.set(Data.java:144)`  
`        at chalkbox.collectors.BlackboardCollector.readSubmissionFile(BlackboardCollector.java:159)`  
`        at chalkbox.collectors.BlackboardCollector.collect(BlackboardCollector.java:45)`  
`        ... 7 more`  
`java.lang.reflect.InvocationTargetException`  
`Exception in thread "main" java.lang.NullPointerException`  
`        at chalkbox.api.ProcessRunner.executeProcess(ProcessRunner.java:45)`  
`        at chalkbox.api.ChalkBox.executeProcess(ChalkBox.java:361)` \
`        at chalkbox.api.ChalkBox.run(ChalkBox.java:170)`  
`        at chalkbox.api.ChalkBox.main(ChalkBox.java:456)`

The `BlackboardCollector.collect` method is passing the string:
`Barry B. Benson`  
`Adam Flayman`  
`Vanessa Bloome`  
`Mooseblood`  
`Rick Astley`  
`Mike Myers`  
`Steve Harwell`  
`Dade Murphy`  
`Kate Libby`  
`Ramon Sanchez`  
`Emmanuel Goldstein`  
`Paul Cook`  
`Joey Pardella`  
`Eugene Belford`  
`Margo Wallace`  
`Lauren Murphy`  
`Danny Devito`  
`Eddie Murphy`  
`Cameron Diaz`  
`John Lithgow`  
`Richo Thomas`  
`Michael Scott`  
`Dwight Schrute`  
`Jim Halpert`  
`Pam Beesly`  
`Ryan Howard`
to `BlackboardCollector.readSubmissionFile`, when this exception is thrown.

**Comment by applebyter** [comment]
Here is the zip file that contains the data that causes the issue.
[2019s2a2-gradebook.zip](https://github.com/BraeWebb/chalkbox/files/3954139/2019s2a2-gradebook.zip)

**Comment by applebyter** [comment]
Error above seems to be fixed, though the fix is not as robust as it could be.
The comment on #16 identifies another apparent error.
